id: fastapi-routes
language: python
rule:
  any:
    - pattern: |
        @$APP.get($$$ARGS)
        def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$APP.get($$$ARGS)
        async def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$APP.post($$$ARGS)
        def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$APP.post($$$ARGS)
        async def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$APP.put($$$ARGS)
        async def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$APP.patch($$$ARGS)
        async def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$APP.delete($$$ARGS)
        async def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$ROUTER.get($$$ARGS)
        async def $FUNC($$$PARAMS):
            $$$BODY
    - pattern: |
        @$ROUTER.post($$$ARGS)
        async def $FUNC($$$PARAMS):
            $$$BODY
message: FastAPI route handler found
severity: info
